import * as admin from "firebase-admin";
import * as dotenv from "dotenv";
import * as path from "path";
import {
  initializeFirebase,
  getFirestore,
  createGeoPoint,
  COLLECTIONS,
} from "../config/firebase";

// Load environment variables
dotenv.config({ path: path.join(__dirname, "../../../.env") });

/**
 * Seed GGV University data with comprehensive structure
 */
async function seedGGVData() {
  try {
    console.log("🌱 Starting GGV data seeding...\n");

    initializeFirebase();
    const db = getFirestore();

    // 1. Create Organization (GGV)
    console.log("📍 Creating organization...");
    const orgId = "ggv-bilaspur";
    const orgRef = db.collection(COLLECTIONS.ORGANIZATIONS).doc(orgId);
    await orgRef.set({
      id: orgId,
      name: "Guru Ghasidas Vishwavidyalaya",
      shortName: "GGV",
      address: "Koni, Bilaspur",
      city: "Bilaspur",
      state: "Chhattisgarh",
      country: "India",
      campusCenter: createGeoPoint(22.131, 82.1495),
      campusBounds: {
        northWest: createGeoPoint(22.1515, 82.134),
        northEast: createGeoPoint(22.1515, 82.1655),
        southWest: createGeoPoint(22.115, 82.134),
        southEast: createGeoPoint(22.115, 82.1655),
      },
      contactEmail: "info@ggu.ac.in",
      contactPhone: "+91-7752-260910",
      website: "https://www.ggu.ac.in",
      timezone: "Asia/Kolkata",
      isActive: true,
      createdAt: admin.firestore.FieldValue.serverTimestamp(),
      updatedAt: admin.firestore.FieldValue.serverTimestamp(),
    });
    console.log("✅ Organization created: GGV\n");

    // 2. Create Departments
    console.log("🏛️  Creating departments...");
    const departments = [
      { id: "dept-cse", code: "CSE", name: "Computer Science & Engineering" },
      {
        id: "dept-ece",
        code: "ECE",
        name: "Electronics & Communication Engineering",
      },
      { id: "dept-ee", code: "EE", name: "Electrical Engineering" },
      { id: "dept-me", code: "ME", name: "Mechanical Engineering" },
      { id: "dept-civil", code: "CIVIL", name: "Civil Engineering" },
      { id: "dept-physics", code: "PHY", name: "Department of Physics" },
      { id: "dept-chemistry", code: "CHEM", name: "Department of Chemistry" },
      { id: "dept-maths", code: "MATH", name: "Department of Mathematics" },
      { id: "dept-lib", code: "LIB", name: "Central Library" },
      { id: "dept-admin", code: "ADMIN", name: "Administration" },
    ];

    for (const dept of departments) {
      await db
        .collection(COLLECTIONS.DEPARTMENTS)
        .doc(dept.id)
        .set({
          id: dept.id,
          organizationId: orgId,
          name: dept.name,
          code: dept.code,
          contactEmail: `${dept.code.toLowerCase()}@ggu.ac.in`,
          isActive: true,
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        });
    }
    console.log(`✅ ${departments.length} departments created\n`);

    // 3. Create Buildings
    console.log("🏢 Creating buildings...");
    const buildings = [
      {
        id: "bldg-engineering",
        name: "Engineering Block A",
        code: "ENG-A",
        location: createGeoPoint(22.1335, 82.147),
        departmentId: "dept-cse",
        buildingType: "Academic",
        floors: 4,
        totalArea: 5000,
        constructionYear: 2010,
      },
      {
        id: "bldg-science",
        name: "Science Block",
        code: "SCI",
        location: createGeoPoint(22.1325, 82.1485),
        departmentId: "dept-physics",
        buildingType: "Academic",
        floors: 3,
        totalArea: 4000,
        constructionYear: 2008,
      },
      {
        id: "bldg-library",
        name: "Central Library",
        code: "LIB",
        location: createGeoPoint(22.131, 82.15),
        departmentId: "dept-lib",
        buildingType: "Library",
        floors: 3,
        totalArea: 3500,
        constructionYear: 2012,
      },
      {
        id: "bldg-admin",
        name: "Administrative Block",
        code: "ADMIN",
        location: createGeoPoint(22.1305, 82.1495),
        departmentId: "dept-admin",
        buildingType: "Administrative",
        floors: 2,
        totalArea: 2500,
        constructionYear: 2005,
      },
      {
        id: "bldg-hostel-boys",
        name: "Boys Hostel Block 1",
        code: "BH-1",
        location: createGeoPoint(22.1345, 82.1515),
        buildingType: "Residential",
        floors: 4,
        totalArea: 6000,
        constructionYear: 2015,
      },
      {
        id: "bldg-hostel-girls",
        name: "Girls Hostel Block 1",
        code: "GH-1",
        location: createGeoPoint(22.1295, 82.1515),
        buildingType: "Residential",
        floors: 4,
        totalArea: 6000,
        constructionYear: 2016,
      },
      {
        id: "bldg-auditorium",
        name: "University Auditorium",
        code: "AUD",
        location: createGeoPoint(22.132, 82.149),
        buildingType: "Auditorium",
        floors: 2,
        totalArea: 3000,
        constructionYear: 2018,
      },
      {
        id: "bldg-sports",
        name: "Sports Complex",
        code: "SPORTS",
        location: createGeoPoint(22.135, 82.151),
        buildingType: "Recreational",
        floors: 2,
        totalArea: 4500,
        constructionYear: 2017,
      },
    ];

    for (const building of buildings) {
      await db
        .collection(COLLECTIONS.BUILDINGS)
        .doc(building.id)
        .set({
          ...building,
          organizationId: orgId,
          address: `${building.name}, GGV Campus, Bilaspur`,
          status: "active" as const,
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        });
    }
    console.log(`✅ ${buildings.length} buildings created\n`);

    // 4. Create Sample Rooms
    console.log("🚪 Creating rooms...");
    const rooms = [
      // Engineering Block A
      {
        buildingId: "bldg-engineering",
        roomNumber: "101",
        floor: 1,
        roomType: "classroom",
        capacity: 60,
        hasAC: true,
        hasProjector: true,
      },
      {
        buildingId: "bldg-engineering",
        roomNumber: "102",
        floor: 1,
        roomType: "lab",
        capacity: 30,
        hasAC: true,
        hasProjector: true,
      },
      {
        buildingId: "bldg-engineering",
        roomNumber: "201",
        floor: 2,
        roomType: "classroom",
        capacity: 80,
        hasAC: true,
        hasProjector: true,
      },
      {
        buildingId: "bldg-engineering",
        roomNumber: "301",
        floor: 3,
        roomType: "lab",
        capacity: 40,
        hasAC: true,
        hasProjector: false,
      },
      // Science Block
      {
        buildingId: "bldg-science",
        roomNumber: "101",
        floor: 1,
        roomType: "lab",
        capacity: 30,
        hasAC: false,
        hasProjector: false,
      },
      {
        buildingId: "bldg-science",
        roomNumber: "201",
        floor: 2,
        roomType: "classroom",
        capacity: 50,
        hasAC: true,
        hasProjector: true,
      },
      // Library
      {
        buildingId: "bldg-library",
        roomNumber: "G01",
        floor: 0,
        roomType: "library",
        capacity: 200,
        hasAC: true,
        hasProjector: false,
      },
      {
        buildingId: "bldg-library",
        roomNumber: "201",
        floor: 2,
        roomType: "library",
        capacity: 100,
        hasAC: true,
        hasProjector: false,
      },
      // Auditorium
      {
        buildingId: "bldg-auditorium",
        roomNumber: "Main Hall",
        floor: 1,
        roomType: "auditorium",
        capacity: 500,
        hasAC: true,
        hasProjector: true,
      },
    ];

    for (let i = 0; i < rooms.length; i++) {
      const room = rooms[i];
      await db.collection(COLLECTIONS.ROOMS).add({
        id: `room-${i + 1}`,
        organizationId: orgId,
        departmentId: "dept-cse",
        ...room,
        status: "active" as const,
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      });
    }
    console.log(`✅ ${rooms.length} rooms created\n`);

    // 5. Create Sample Users
    console.log("👥 Creating users...");
    const users = [
      {
        id: "user-admin",
        email: "admin@ggu.ac.in",
        name: "Campus Administrator",
        role: "admin" as const,
        permissions: {
          canCreateIssues: true,
          canResolveIssues: true,
          canAssignIssues: true,
          canViewAllIssues: true,
          canManageUsers: true,
        },
      },
      {
        id: "user-facility",
        email: "facility@ggu.ac.in",
        name: "Facility Manager",
        role: "facility_manager" as const,
        permissions: {
          canCreateIssues: true,
          canResolveIssues: true,
          canAssignIssues: true,
          canViewAllIssues: true,
          canManageUsers: false,
        },
      },
      {
        id: "user-student1",
        email: "student1@ggu.ac.in",
        name: "Deepak Soni",
        role: "student" as const,
        departmentId: "dept-cse",
        permissions: {
          canCreateIssues: true,
          canResolveIssues: false,
          canAssignIssues: false,
          canViewAllIssues: false,
          canManageUsers: false,
        },
      },
    ];

    for (const user of users) {
      await db
        .collection(COLLECTIONS.USERS)
        .doc(user.id)
        .set({
          ...user,
          organizationId: orgId,
          isActive: true,
          createdAt: admin.firestore.FieldValue.serverTimestamp(),
          updatedAt: admin.firestore.FieldValue.serverTimestamp(),
        });
    }
    console.log(`✅ ${users.length} users created\n`);

    // 6. Create Sample Issues
    console.log("🔧 Creating sample issues...");
    const issues = [
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-cse",
        title: "Broken AC in Classroom 201",
        description:
          "Air conditioning unit not working, making the classroom unbearably hot",
        category: "HVAC",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "WiFi Not Working in Reading Hall",
        description:
          "Students unable to access online resources due to WiFi failure",
        category: "Network",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-physics",
        title: "Water Leakage in Lab 101",
        description: "Ceiling is leaking water, damaging equipment",
        category: "Plumbing",
        severity: 9,
        priority: "critical",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-hostel-boys",
        title: "Broken Bathroom Door",
        description: "Door lock is broken in Room 305 bathroom",
        category: "Maintenance",
        severity: 4,
        priority: "low",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-cse",
        title: "Projector Not Working in Lab 102",
        description: "Display projector shows no signal",
        category: "Electrical",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-admin",
        title: "Power Outage in Main Office",
        description:
          "Electrical circuit breaker tripped, affecting multiple rooms",
        category: "Electrical",
        severity: 8,
        priority: "critical",
        submissionType: "text",
        reportedBy: "user-admin",
        reportedByRole: "admin",
      },
      {
        buildingId: "bldg-canteen",
        title: "Blocked Drainage in Kitchen",
        description:
          "Kitchen sink drainage completely blocked causing water backup",
        category: "Plumbing",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-hostel-girls",
        title: "Broken Window in Room 204",
        description:
          "Window pane cracked after storm, needs immediate replacement",
        category: "Maintenance",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-sports",
        title: "Gym Equipment Malfunction",
        description:
          "Treadmill motor making strange noises and stopping intermittently",
        category: "Maintenance",
        severity: 4,
        priority: "low",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "Insufficient Lighting in Study Area",
        description:
          "Multiple tube lights not working in the main reading hall",
        category: "Electrical",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-cse",
        title: "Computer Lab AC Overheating",
        description: "AC in server room showing high temperature warnings",
        category: "HVAC",
        severity: 9,
        priority: "critical",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-chemistry",
        title: "Fume Hood Not Working",
        description:
          "Exhaust system failure in chemistry lab poses safety risk",
        category: "HVAC",
        severity: 8,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-hostel-boys",
        title: "Water Supply Interruption",
        description: "No water in 3rd floor since morning",
        category: "Plumbing",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-admin",
        title: "Broken Elevator",
        description: "Elevator stuck between floors, needs immediate attention",
        category: "Maintenance",
        severity: 9,
        priority: "critical",
        submissionType: "text",
        reportedBy: "user-admin",
        reportedByRole: "admin",
      },
      {
        buildingId: "bldg-canteen",
        title: "Refrigerator Not Cooling",
        description:
          "Main refrigerator temperature rising, food safety concern",
        category: "Electrical",
        severity: 8,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "Leaking Roof in Archives",
        description:
          "Water seeping through roof damaging rare books collection",
        category: "Plumbing",
        severity: 9,
        priority: "critical",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-sports",
        title: "Damaged Floor Tiles in Basketball Court",
        description: "Cracked tiles creating safety hazard for players",
        category: "Maintenance",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-hostel-girls",
        title: "WiFi Signal Weak on 4th Floor",
        description:
          "Internet connectivity issues affecting students' online classes",
        category: "Network",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-cse",
        title: "Fire Alarm System Malfunction",
        description: "Fire alarm randomly triggering without cause",
        category: "Electrical",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-physics",
        title: "Lab Equipment Power Fluctuation",
        description: "Voltage instability damaging sensitive equipment",
        category: "Electrical",
        severity: 8,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      // Additional 40+ scattered issues for better heatmap coverage
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-ece",
        title: "Network Cable Damage in ECE Lab",
        description: "Ethernet ports not functioning in multiple workstations",
        category: "Network",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "AC Vent Blocked in Reference Section",
        description: "Poor air circulation causing discomfort",
        category: "HVAC",
        severity: 4,
        priority: "low",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-hostel-boys",
        title: "Hot Water System Failure",
        description: "No hot water in ground floor bathrooms",
        category: "Plumbing",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-chemistry",
        title: "Emergency Shower Not Working",
        description: "Safety equipment malfunction in lab",
        category: "Plumbing",
        severity: 9,
        priority: "critical",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-auditorium",
        title: "Sound System Feedback Issue",
        description: "Microphone producing loud feedback noise",
        category: "Electrical",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-admin",
        reportedByRole: "admin",
      },
      {
        buildingId: "bldg-sports",
        title: "Swimming Pool Filter Malfunction",
        description: "Water not being properly filtered",
        category: "Maintenance",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-me",
        title: "Workshop Ventilation Poor",
        description: "Exhaust fans not working properly",
        category: "HVAC",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-hostel-girls",
        title: "Water Cooler Not Working",
        description: "No cold water available on 2nd floor",
        category: "Electrical",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "WiFi Drops Frequently in Digital Library",
        description: "Constant connection interruptions",
        category: "Network",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-admin",
        title: "Printer Network Issues",
        description: "Network printers offline in admin office",
        category: "Network",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-admin",
        reportedByRole: "admin",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-physics",
        title: "Gas Leak in Lab Storage",
        description: "Smell of gas detected in storage area",
        category: "Maintenance",
        severity: 10,
        priority: "critical",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-civil",
        title: "Unstable Internet in CAD Lab",
        description: "Students unable to submit assignments online",
        category: "Network",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-hostel-boys",
        title: "Corridor Lights Flickering",
        description: "Multiple lights on 2nd floor flickering",
        category: "Electrical",
        severity: 4,
        priority: "low",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-sports",
        title: "Badminton Court Lighting",
        description: "Several lights not working in indoor court",
        category: "Electrical",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "Toilet Flush Not Working",
        description: "Broken flush in 1st floor restroom",
        category: "Plumbing",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-auditorium",
        title: "Stage Lighting Control Panel Error",
        description: "Cannot control individual lights",
        category: "Electrical",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-ee",
        title: "Power Lab Equipment Short Circuit",
        description: "Circuit breaker keeps tripping",
        category: "Electrical",
        severity: 8,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-hostel-girls",
        title: "Room Heater Not Functioning",
        description: "Electric heater not turning on in Room 301",
        category: "Electrical",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-maths",
        title: "Projector Bulb Dim",
        description: "Projector display very dim, hard to see",
        category: "Electrical",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-admin",
        title: "WiFi Router Overheating",
        description: "Main router showing temperature warnings",
        category: "Network",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-cse",
        title: "Server Room AC Critical",
        description: "Temperature rising above safe levels",
        category: "HVAC",
        severity: 9,
        priority: "critical",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "Water Fountain Pressure Low",
        description: "Very weak water flow from fountain",
        category: "Plumbing",
        severity: 4,
        priority: "low",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-hostel-boys",
        title: "Washing Machine Not Draining",
        description: "Common area washing machine water not draining",
        category: "Maintenance",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-sports",
        title: "Tennis Court Net Damaged",
        description: "Net torn and needs replacement",
        category: "Maintenance",
        severity: 4,
        priority: "low",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-chemistry",
        title: "Sink Drainage Slow",
        description: "Lab sink draining very slowly",
        category: "Plumbing",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-auditorium",
        title: "AC Not Cooling Green Room",
        description: "Backstage area too hot",
        category: "HVAC",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-admin",
        reportedByRole: "admin",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-me",
        title: "CNC Machine Coolant Leak",
        description: "Coolant leaking from machine",
        category: "Maintenance",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-hostel-girls",
        title: "Internet Speed Very Slow",
        description: "Cannot attend online classes properly",
        category: "Network",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "Photocopy Machine Jam",
        description: "Paper getting stuck frequently",
        category: "Maintenance",
        severity: 4,
        priority: "low",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-admin",
        title: "Leaking Ceiling During Rain",
        description: "Water coming through ceiling in records room",
        category: "Plumbing",
        severity: 8,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-admin",
        reportedByRole: "admin",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-physics",
        title: "Oscilloscope Power Issues",
        description: "Equipment keeps shutting down",
        category: "Electrical",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-ece",
        title: "Antenna Lab WiFi Dead Zone",
        description: "No WiFi signal in corner of lab",
        category: "Network",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-hostel-boys",
        title: "Common Room TV Not Working",
        description: "Display shows no signal",
        category: "Electrical",
        severity: 4,
        priority: "low",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-sports",
        title: "Locker Room Shower Cold",
        description: "Hot water system not working",
        category: "Plumbing",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "Printer Out of Toner",
        description: "Student printer not printing",
        category: "Maintenance",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-auditorium",
        title: "Backstage Door Lock Broken",
        description: "Security concern with broken lock",
        category: "Maintenance",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-admin",
        reportedByRole: "admin",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-civil",
        title: "Surveying Equipment Storage Lock",
        description: "Cannot access equipment due to broken lock",
        category: "Maintenance",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-hostel-girls",
        title: "Geyser Leaking in Bathroom",
        description: "Water dripping from water heater",
        category: "Plumbing",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-chemistry",
        title: "Chemical Storage AC Failed",
        description: "Temperature control critical for stored chemicals",
        category: "HVAC",
        severity: 9,
        priority: "critical",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-admin",
        title: "Security Camera Not Recording",
        description: "Main entrance camera offline",
        category: "Electrical",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-admin",
        reportedByRole: "admin",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-ee",
        title: "Transformer Making Noise",
        description: "Unusual humming sound from transformer",
        category: "Electrical",
        severity: 8,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "Database Server Slow",
        description: "Library management system very slow",
        category: "Network",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-hostel-boys",
        title: "Mess Hall Fan Not Working",
        description: "Ceiling fan in dining area stopped",
        category: "Electrical",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-sports",
        title: "Football Field Sprinkler Broken",
        description: "Irrigation system not watering properly",
        category: "Plumbing",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-maths",
        title: "Smart Board Not Responding",
        description: "Touch screen not working",
        category: "Electrical",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-auditorium",
        title: "Emergency Exit Light Off",
        description: "Safety lighting not functional",
        category: "Electrical",
        severity: 8,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-facility",
        reportedByRole: "facility_manager",
      },
      {
        buildingId: "bldg-engineering",
        departmentId: "dept-me",
        title: "3D Printer Connectivity Issues",
        description: "Cannot send files to printer over network",
        category: "Network",
        severity: 5,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-hostel-girls",
        title: "Study Room AC Too Cold",
        description: "Temperature setting not adjustable",
        category: "HVAC",
        severity: 4,
        priority: "low",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-library",
        departmentId: "dept-lib",
        title: "Book Return Slot Jammed",
        description: "Cannot return books through slot",
        category: "Maintenance",
        severity: 4,
        priority: "low",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
      {
        buildingId: "bldg-admin",
        title: "Biometric Attendance Not Working",
        description: "Fingerprint scanner error",
        category: "Electrical",
        severity: 7,
        priority: "high",
        submissionType: "text",
        reportedBy: "user-admin",
        reportedByRole: "admin",
      },
      {
        buildingId: "bldg-science",
        departmentId: "dept-physics",
        title: "Microscope Illuminator Burnt",
        description: "Light source not working in microscope",
        category: "Electrical",
        severity: 6,
        priority: "medium",
        submissionType: "text",
        reportedBy: "user-student1",
        reportedByRole: "student",
      },
    ];

    for (let i = 0; i < issues.length; i++) {
      const issue = issues[i];
      const building = buildings.find((b) => b.id === issue.buildingId);
      if (!building) continue;

      await db.collection(COLLECTIONS.ISSUES).add({
        ...issue,
        organizationId: orgId,
        location: building.location,
        status: i < 2 ? "open" : "in_progress",
        createdAt: admin.firestore.FieldValue.serverTimestamp(),
        updatedAt: admin.firestore.FieldValue.serverTimestamp(),
      });
    }
    console.log(`✅ ${issues.length} issues created\n`);

    console.log("✅ GGV data seeding completed successfully!");
    console.log(`
📊 Summary:
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
✓ 1 Organization (GGV)
✓ ${departments.length} Departments
✓ ${buildings.length} Buildings
✓ ${rooms.length} Rooms
✓ ${users.length} Users
✓ ${issues.length} Sample Issues
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
    `);

    process.exit(0);
  } catch (error) {
    console.error("❌ Error seeding GGV data:", error);
    process.exit(1);
  }
}

// Run seeding
seedGGVData();
